In [1]:
from pathlib import Path
import pandas as pd

In [2]:
current_file_path = Path(__vsc_ipynb_file__)
main_directory = current_file_path.parents[1]
export_path = main_directory.joinpath("data/ex_bio")
exBio_TallyGabi_path = main_directory.joinpath("references/expanded_TallyGaBi_biogenic.xlsx")
df_exBio_TallyGabi = pd.read_excel(exBio_TallyGabi_path, sheet_name="ex_bio")

In [3]:
cleaned_tally_path = main_directory.joinpath("data/lca_results/cleaned/tally")
csv_files = [file for file in cleaned_tally_path.glob('*.csv')]

In [4]:
incons_material_name = (
        "Lightweight concrete, 2501-3000 psi, 0-19% fly ash and/or slag",
        "Lightweight concrete, 2501-3000 psi, 20-29% fly ash",
        "Lightweight concrete, 3001-4000 psi, 0-19% fly ash and/or slag",
        "Lightweight concrete, 3001-4000 psi, 20-29% fly ash",
        "Lightweight concrete, 4001-5000 psi, 0-19% fly ash and/or slag",
        "Lightweight concrete, 4001-5000 psi, 20-29% fly ash",
        "Lightweight concrete; 2501-3000 psi; 0-19% fly ash and/or slag",
        "Lightweight concrete; 4001-5000 psi; 0-19% fly ash and/or slag",
        "Lightweight concrete; 4001-5000 psi; 20-29% fly ash",
        "Polyamide, nylon 6.6",
        "Polystyrene board (XPS), Pentane foaming agent",
        "Polystyrene board (XPS); Pentane foaming agent",
        "Structural concrete, 0-2500 psi, 20-29% fly ash",
        "Structural concrete, 0-2500 psi, 30-39% fly ash",
        "Structural concrete, 0-2500 psi, 30-39% slag",
        "Structural concrete, 0-2500 psi, 30-39% slag",
        "Structural concrete, 2501-3000 psi, >20% fly ash and >30% slag",
        "Structural concrete, 2501-3000 psi, 0-19% fly ash and/or slag",
        "Structural concrete, 2501-3000 psi, 20-29% fly ash",
        "Structural concrete, 2501-3000 psi, 30-39% fly ash",
        "Structural concrete, 3001-4000 psi, >20% fly ash and >30% slag",
        "Structural concrete, 3001-4000 psi, >50% slag",
        "Structural concrete, 3001-4000 psi, 0-19% fly ash and/or slag",
        "Structural concrete, 3001-4000 psi, 20-29% fly ash",
        "Structural concrete, 3001-4000 psi, 30-39% fly ash",
        "Structural concrete, 3001-4000 psi, 30-39% slag",
        "Structural concrete, 3001-4000 psi, 40-49% fly ash",
        "Structural concrete, 3001-4000 psi, 40-49% slag",
        "Structural concrete, 4001-5000 psi, >20% fly ash and >30% slag",
        "Structural concrete, 4001-5000 psi, 0-19% fly ash and/or slag",
        "Structural concrete, 4001-5000 psi, 20-29% fly ash",
        "Structural concrete, 4001-5000 psi, 30-39% fly ash",
        "Structural concrete, 4001-5000 psi, 30-39% slag",
        "Structural concrete, 4001-5000 psi, 40-49% fly ash",
        "Structural concrete, 4001-5000 psi, 40-49% slag",
        "Structural concrete, 5001-6000 psi, 0-19% fly ash and/or slag",
        "Structural concrete, 5001-6000 psi, 20-29% fly ash",
        "Structural concrete, 5001-6000 psi, 30-39% fly ash",
        "Structural concrete, 6001-8000 psi, 0-19% fly ash and/or slag",
        "Structural concrete, 6001-8000 psi, 20-29% fly ash",
        "Structural concrete, 6001-8000 psi, 40-49% fly ash",
        "Structural concrete; 2501-3000 psi; 0-19% fly ash and/or slag",
        "Structural concrete; 3001-4000 psi; 0-19% fly ash and/or slag",
        "Structural concrete; 4001-5000 psi; 0-19% fly ash and/or slag",
        "Structural concrete; 4001-5000 psi; 20-29% fly ash",
    )

In [5]:
test_file = csv_files[2]
test_file_stem = test_file.stem

In [6]:
test_file_stem

'AB003_01'

In [7]:
test_df = pd.read_csv(test_file).reset_index(names="original_index")

In [8]:
test_df_a1_a3 = test_df.iloc[::5].reset_index(drop=True)
test_df_a1_a3.index = 'element_'+test_df_a1_a3.index.astype(str)
test_df_a4 = test_df.iloc[1::5].reset_index(drop=True)
test_df_a4.index = 'element_'+test_df_a4.index.astype(str)
test_df_b2_b5 = test_df.iloc[2::5].reset_index(drop=True)
test_df_b2_b5.index = 'element_'+test_df_b2_b5.index.astype(str)
test_df_c2_c4 = test_df.iloc[3::5].reset_index(drop=True)
test_df_c2_c4.index = 'element_'+test_df_c2_c4.index.astype(str)
test_df_d = test_df.iloc[4::5].reset_index(drop=True)
test_df_d.index = 'element_'+test_df_d.index.astype(str)

In [9]:
test_df_a1_a3_ex_bio = test_df_a1_a3.copy() 
test_df_b2_b5_ex_bio = test_df_b2_b5.copy() 
test_df_c2_c4_ex_bio = test_df_c2_c4.copy()
test_df_a1_a3_ex_bio_for_replacement_impacts = test_df_a1_a3.copy() 
test_df_a4_ex_bio_for_replacement_impacts = test_df_a4.copy() 
test_df_c2_c4_ex_bio_for_replacement_impacts = test_df_c2_c4.copy()

In [12]:
test_df_a1_a3_ex_bio["Global Warming Potential Total (kgCO2eq)"] = test_df_a1_a3_ex_bio[
    "Material Name"
    ].map(df_exBio_TallyGabi.set_index("name")["gwe_mfg"]) * test_df_a1_a3_ex_bio["Mass Total (kg)"]
test_df_a1_a3_ex_bio.loc[
    test_df_a1_a3_ex_bio["Material Name"].isin(incons_material_name),
    "Global Warming Potential Total (kgCO2eq)"
] = test_df_a1_a3["Global Warming Potential Total (kgCO2eq)"]

test_df_c2_c4_ex_bio["Global Warming Potential Total (kgCO2eq)"] = test_df_c2_c4_ex_bio[
    "Material Name"
    ].map(df_exBio_TallyGabi.set_index("name")["gwe_eol"]) * test_df_a1_a3_ex_bio["Mass Total (kg)"]
test_df_c2_c4_ex_bio.loc[
    test_df_c2_c4_ex_bio["Material Name"].isin(incons_material_name),
    "Global Warming Potential Total (kgCO2eq)"
] = test_df_c2_c4["Global Warming Potential Total (kgCO2eq)"]

In [13]:
test_df_a1_a3_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"] = test_df_a1_a3_ex_bio_for_replacement_impacts[
    "Material Name"
    ].map(df_exBio_TallyGabi.set_index("name")["gwe_mfg"]) * test_df_b2_b5_ex_bio["Mass Total (kg)"]
test_df_a4_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"] = test_df_a4_ex_bio_for_replacement_impacts[
    "Global Warming Potential Total (kgCO2eq)"
    ] * test_df_b2_b5_ex_bio["Mass Total (kg)"] / test_df_a1_a3_ex_bio_for_replacement_impacts["Mass Total (kg)"]
test_df_c2_c4_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"] = test_df_c2_c4_ex_bio_for_replacement_impacts[
    "Material Name"
    ].map(df_exBio_TallyGabi.set_index("name")["gwe_eol"]) * test_df_b2_b5_ex_bio["Mass Total (kg)"]
test_df_b2_b5_ex_bio["Global Warming Potential Total (kgCO2eq)"] = (
    test_df_a1_a3_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"]
    + test_df_a4_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"] 
    + test_df_c2_c4_ex_bio_for_replacement_impacts["Global Warming Potential Total (kgCO2eq)"]
)
test_df_b2_b5_ex_bio.loc[
    test_df_b2_b5_ex_bio["Material Name"].isin(incons_material_name),
    "Global Warming Potential Total (kgCO2eq)"
] = test_df_b2_b5["Global Warming Potential Total (kgCO2eq)"]

In [14]:
test_df_a1_a3_ex_bio["Global Warming Potential Total (kgCO2eq)"].sum()

np.float64(597540.9805609449)

In [15]:
test_df_a1_a3_ex_bio[["Mass Total (kg)","Global Warming Potential Total (kgCO2eq)"]]

             Mass Total (kg)  Global Warming Potential Total (kgCO2eq)
element_0           0.353424                                  3.202022
element_1        1500.963456                              13598.728911
element_2           3.984431                                 36.098945
element_3          80.420625                                728.610866
element_4         150.887156                               1367.037633
...                      ...                                       ...
element_361         0.480587                                  0.571899
element_362       220.380005                               2688.636059
element_363      1027.344390                               1376.641483
element_364       212.011492                               2586.540208
element_365       905.803437                               1213.776606

[366 rows x 2 columns]

In [16]:
test_df_a1_a3[["Mass Total (kg)","Global Warming Potential Total (kgCO2eq)"]]

             Mass Total (kg)  Global Warming Potential Total (kgCO2eq)
element_0           0.353424                                  3.177282
element_1        1500.963456                              13493.661469
element_2           3.984431                                 35.820034
element_3          80.420625                                722.981422
element_4         150.887156                               1356.475532
...                      ...                                       ...
element_361         0.480587                                  0.576705
element_362       220.380005                               2710.674059
element_363      1027.344390                               1376.641483
element_364       212.011492                               2607.741357
element_365       905.803437                               1213.776606

[366 rows x 2 columns]

In [17]:
test_df_a1_a3_ex_bio["Global Warming Potential Total (kgCO2eq)"].sum()

np.float64(597540.9805609449)

In [18]:
test_df_a4["Global Warming Potential Total (kgCO2eq)"].sum()

np.float64(13566.296991226483)

In [19]:
test_df_b2_b5_ex_bio["Global Warming Potential Total (kgCO2eq)"].sum()

np.float64(148461.94399254565)

In [20]:
test_df_c2_c4_ex_bio["Global Warming Potential Total (kgCO2eq)"].sum()

np.float64(156638.62084747196)

In [21]:
pd.concat([test_df_a1_a3_ex_bio, test_df_a4, test_df_b2_b5_ex_bio, test_df_c2_c4_ex_bio, test_df_d]).set_index("original_index").sort_index().to_csv("test.csv")

In [22]:
test_df_d

,original_index,CLF Model ID,Revit design option,Revit general category,Revit category,Revit type,Revit family name,Revit material name,Revit building element,Thickness of material (m),...,Smog Formation Potential Total (kgO3eq),Primary Energy Demand Total (MJ),Non-renewable Energy Demand Total (MJ),Renewable Energy Demand Total (MJ),Mass Total (kg),Tool,CLF Omni,file_name_before_merge,MQ_1,MQ_2
element_0,4,AB003_01,Main Model,Curtainwall Mullions,Curtainwall Mullions,Mullion,Rectangular Mullion: *SF 2 x 6 x 1 SSG Edge,METAL_Framing,Undefined,0.000000,...,-0.086235,-26.012010,-15.974767,-10.001901,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_1,9,AB003_01,Main Model,Curtainwall Mullions,Curtainwall Mullions,Mullion,Rectangular Mullion: Alum - 2 x 4 1/2 Champine,Metal - Champaine,Undefined,0.000000,...,-366.235083,-110470.910360,-67843.548210,-42477.265804,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_2,14,AB003_01,Main Model,Curtainwall Mullions,Curtainwall Mullions,Mullion,Rectangular Mullion: Alum - 2 x 4 1/2 Dark Grey,"Aluminum, Anodized Dark Grey",Undefined,0.000000,...,-0.972201,-293.254119,-180.096280,-112.759396,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_3,19,AB003_01,Main Model,Curtainwall Mullions,Curtainwall Mullions,Mullion,Rectangular Mullion: Alum - 2 x 4,"Aluminum, Anodized Dark Grey",Undefined,0.000000,...,-19.622633,-5918.958025,-3635.012265,-2275.903697,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_4,24,AB003_01,Main Model,Curtainwall Mullions,Curtainwall Mullions,Mullion,Rectangular Mullion: Alum - 2 x 6,"Aluminum, Anodized Dark Grey",Undefined,0.000000,...,-36.816466,-11105.294680,-6820.099450,-4270.106514,NaN,TallyLCA,NaN,Not a merged file,Other,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
element_361,1809,AB003_01,Main Model,Walls,Walls,Wall,INT_Limestone 4 - Air 2 3/8 - 5 Ply CLT 6 7/8...,Wood - CLT 1 Hour,Interiors,0.174625,...,0.000000,0.000000,0.000000,0.000000,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_362,1814,AB003_01,Main Model,Windows,Windows,FamilyInstance,CP_GL_Window-Single Unit: Casement Left,"Aluminum, Anodized Dark Grey",Undefined,0.000000,...,-73.166162,-22082.076483,-13575.408297,-8506.668186,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_363,1819,AB003_01,Main Model,Windows,Windows,FamilyInstance,CP_GL_Window-Single Unit: Casement Left,GLASS_Clear - 1 Insulated,Undefined,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_364,1824,AB003_01,Main Model,Windows,Windows,FamilyInstance,CP_GL_Window-Single Unit: Casement Right,"Aluminum, Anodized Dark Grey",Undefined,0.000000,...,-70.387815,-21243.551541,-13059.907933,-8183.643607,NaN,TallyLCA,NaN,Not a merged file,Other,Other
element_365,1829,AB003_01,Main Model,Windows,Windows,FamilyInstance,CP_GL_Window-Single Unit: Casement Right,GLASS_Clear - 1 Insulated,Undefined,0.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,TallyLCA,NaN,Not a merged file,Other,Other